### ISSUE TITLE
[Open talk] Reject timesheet

### ISSUE THREAD

**Issue by hiepngoxuan** [ncc-erp/ncc-erp-timesheet#225]
- Create a new API to reject the timesheet
- input: a list of employee email
- find all open talk timesheets logged by those employees in the current week and mark them as rejected

Mezon: gửi một list displayName e.g. Hiep Ngo Xuan
startTime vs endTime (thời gian bắt đầu và kết thúc join opentalk)

Timesheet: mapping displayName với user 
tạo một table để lưu thông tin opentalk của từng người

user_opentalk
id
start_time
end_time
total_time
user_id (mapping với user)

- API: public cho Mezon call
```
payload: {
   opentalk: [
       {
             userName: "A Nguyen Van",
             startTime: "",
             endTime: ""
       }
    ]
}
```

Thêm 1 column display thời gian join opentalk thực tế (chỉ hiển thị với task: Opentalk)
khi PM approve
- nếu trường hợp user join ít hơn thời gian quy định -> show warning
- nếu đủ -> approve thành công
![image](https://github.com/user-attachments/assets/5c14c375-3d59-4520-b21c-ff4cd63c43c1)

**Comment by thangngxuan-ncc** [comment]
- Chức năng: Reject log timesheet opentalk ở trạng khái Pending, Approved, Rejected(Không áp dụng với opentalk ở trạng thái New) trong tuần hiện tại của các user có email trùng với email được truyền vào.
- Endpoint: /api/external/timesheet/reject-opentalk
- Method: POST
- Headers: Cần header chứa `securityCode`
- requestBody: JSON chứa thuộc tính employees là mảng chứa các email. Ví dụ:
```
{
    employees: ["thang.nguyenxuan@ncc.asia","admin@ncc.asia"]
}
```
- Response:
   - Thành công: `"success": true`
```
{
  "result": null,
  "targetUrl": null,
  "success": true,
  "error": null,
  "unAuthorizedRequest": false,
  "__abp": true
}
```
  - Thất bại: `"success": false` kèm thông tin lỗi.
```
{
  "result": null,
  "targetUrl": null,
  "success": false,
  "error": {
    "code": 0,
    "message": "SecretCode does not match! Timesheet: 678 != 12345679",
    "details": null,
    "validationErrors": null
  },
  "unAuthorizedRequest": false,
  "__abp": true
}
```

**Comment by hiepngoxuan** [comment]
endpoint: `/api/external/timesheet/reject-opentalk`
requestBody: 
```
{
    employes: ["thang.nguyenxuan@ncc.asia","admin@ncc.asia"]
}
```

**Comment by thangngxuan-ncc** [comment]
- Chức năng: Lưu thông tin thời gian tham gia opentalk của user
- Endpoint: /api/external/timesheet/opentalk
- Method: POST
- Headers: Cần header chứa `securityCode`
- requestBody: JSON array chứ các thuộc tính: fullName, startTime, endTime. Ví dụ:
```
[
    {
        "FullName":"A Nguyen Van",
        "startTime":"2024-08-04T10:00:00.000+07:00",
        "endTime":"2024-08-04T12:00:00.000+07:00"
    },
    {
        "FullName":"B Nguyen Van",
        "startTime":"2024-08-04T11:00:00.000+07:00",
        "endTime":"2024-08-04T12:00:00.000+07:00"
    }
]
```
- Response:
   - Thành công: `"success": true`
```
{
  "result": null,
  "targetUrl": null,
  "success": true,
  "error": null,
  "unAuthorizedRequest": false,
  "__abp": true
}
```
  - Thất bại: `"success": false` kèm thông tin lỗi.
```
{
  "result": null,
  "targetUrl": null,
  "success": false,
  "error": {
    "code": 0,
    "message": "SecretCode does not match! Timesheet: 678 != 12345679",
    "details": null,
    "validationErrors": null
  },
  "unAuthorizedRequest": false,
  "__abp": true
}
```
